### ISSUE TITLE
Update for new BIMserver

### ISSUE THREAD

**Issue by walterogrady** [aothms/python-bimserver-client#1]
First off, I'd like to let you know that this piece of code is really useful and saved me a lot of time.

Second, the latest versions (pre-release) of BIMserver have renamed `Bimsie1AuthInterface` to `AuthInterface`.

Keep up the good work.

**Comment by aothms** [comment]
Thanks. 

> latest versions (pre-release) of BIMserver have renamed Bimsie1AuthInterface to AuthInterface

I have been notified of this issue before. Maybe we can somehow check the version of the running BIMserver prior to attempting login? Or alternatively have a keyword arg `version="1.5"` somewhere? Pull requests welcome!

**Comment by walterogrady** [comment]
How about creating two releases? One for BimServer 1.4 and the other for 1.5.

**Comment by aothms** [comment]
I would be more in favour of a single version for both (and future ...) releases. For end-users it would also be nice to be able to use the same python code base on multiple BIMserver I think.

**Comment by aothms** [comment]
Fixed in 73855f61bbf75279897fcd14e82c9624858ff133
