### ISSUE TITLE
Downloading from bimserver

### ISSUE THREAD

**Issue by Krande** [aothms/python-bimserver-client#3]
First of all, thank you for sharing the python client sample! 

I was just playing around with some of the ServiceInterface operations and I ran into some problems with the "download" method.

I tried hacking together something I thought would work, but I am pretty sure I lacking some fundamental understanding of the various components in the api to get it to work properly.

So with the code I came up with (shown below) 

``` python
project_name="MyProject"
client = bimserver_api.api(bimserver_url, username, password)
projects = client.ServiceInterface.getProjectsByName(name=project_name)
project = projects[0]
serializer = client.ServiceInterface.getSerializerByName(serializerName='Ifc4 (Streaming)')
serializer_id = serializer.get('oid')

topicId = client.ServiceInterface.download(
    roids=[project.get('lastRevisionId')],
    serializerOid=serializer_id,
    query="",
    sync="false",
)
res = client.ServiceInterface.getDownloadData(
    topicId=topicId
)

```
results in the following exception
```
Exception: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
```

Any chance you would have some sample code covering the download steps, or if not perhaps point me in the right direction towards figuring out this on my own?

I did do some quick research into the error message itself and came across a couple of posts that at least describe a similar error message, but with my limited experience with http api's in general the information does not really help me that much (yet).

* https://stackoverflow.com/questions/26925058/no-content-to-map-due-to-end-of-input-jackson-parser
* https://community.atlassian.com/t5/Answers-Developer-Questions/No-content-to-map-to-Object-due-to-end-of-inputjava-io/qaq-p/482426

Lastly, if you want, I could contribute some extra examples to the repository based on whatever I end up with. Maybe create a class wrapping around the api giving some basic pull\push with optional checkin\checkout behaviours. I think having a collection of "best practices" for querying\uploading\downloading using a python-api would be a nice addition! 

Best Regards
Kristoffer

**Comment by aothms** [comment]
Hi thanks for the issue. Not an expert on BIMserver API itself. Never used `getDownloadData()`. I've always used `urllib.request.urlopen()` and a manually constructed download link. There are two download patterns in the BIMServer javascript API: https://github.com/opensourceBIM/BIMserver-JavaScript-API/blob/74b42a77f264a36952e8b7ffe41af99dd0c0c4ca/bimserverclient.js#L257

I think if we can implement a similar download() method in the python client, that would be wonderful. PRs are open for additional samples as well. Thanks in advance!

**Comment by Krande** [comment]
Thanks for the quick response! 

Okay so if I read the javascript method correctly, it just generates a download url. So a python equivalent should be something similar to this:

``` python
project_name="MyProject"
client = bimserver_api.api(bimserver_url, username, password)
projects = client.ServiceInterface.getProjectsByName(name=project_name)
project = projects[0]
serializer = client.ServiceInterface.getSerializerByName(serializerName='Ifc4 (Streaming)')
serializer_id = serializer.get('oid')

topicId = client.ServiceInterface.download(
    roids=[project.get('lastRevisionId')],
    serializerOid=serializer_id,
    query="",
    sync="false",
)

download_url = f"{bimserver_url}/download?token={client.token}&topicId={topicId}"
res = request.urlopen(download_url)
with open('downloaded.ifc', 'wb') as d:
    d.write(res.read())
```

It is still not downloading anything, but hopefully I am one step closer to a working download method. Could there be any configurations I need to do on my bimserver to allow downloads from the api endpoint? And probably there is something I am missing in my "client.ServiceInterface.download" request.

I'll keep on trying to get it working. Any tips along the way is much appreciated :)

Best Regards
Kristoffer

**Comment by Krande** [comment]
Okay, I figured it out! After getting a bit more familiar with this I figured the issue https://github.com/opensourceBIM/BIMserver/issues/1059 was the same. My query string was empty and was therefore not successful. With the code below, I am able to download the latest revision of my model from a bimserver using python.

``` python
import json
from urllib import request
project_name = "MyProject"
client = bimserver_api.api(bimserver_url, username, password)
projects = client.ServiceInterface.getProjectsByName(name=project_name)
project = projects[0]
serializer = client.ServiceInterface.getSerializerByName(serializerName='Ifc4 (Streaming)')
serializer_id = serializer.get('oid')
roid = projects[0].get('lastRevisionId')
topicId = client.ServiceInterface.download(
    roids=[roid],
    serializerOid=serializer_id,
    query=json.dumps({}),
    sync='false',
)

download_url = f"{bimserver_url}/download?token={client.token}&zip=on&topicId={topicId}"
res = request.urlopen(download_url)
with open('res.zip', 'wb') as d:
    d.write(res.read())
```

**Comment by aothms** [comment]
Ok, great. Is the  `json.dumps` necessary, or can it just be an empty object in itself?

> I could contribute some extra examples to the repository based on whatever I end up with

I think if you can add this example to the README people would appreciate it. Downloading is a pretty common task I guess.

**Comment by Krande** [comment]
I tried with an empty string and None with no luck. I will add the example to the README.md asap!
